### PR TITLE
Rewrite of WindowChromeBehavior to contain everything previously contained in WindowChrome, WindowChromeWorker and WindowChromeBehavior

### PR DESCRIPTION
**Pull request by batzen**
Tested this with latest versions of Fluent.Ribbon and MahApps from their respective develop branches.

### CODE REVIEW

**Comment by batzen** [comment]
@punker76 Could you have a look at this, so we can finally merge it?

**Comment by batzen** [comment]
@punker76 ping

**Comment by punker76** [comment]
@batzen I'll look in the next 2 weeks

**Comment by batzen** [comment]
@punker76 Don't want to put pressure on you, but it would be nice if you could have a look at this. ;-)

**Comment by batzen** [comment]
This PR now also contains all changes related to GlowWindow.

GlassFrameThickness and all code related to it is gone now.

**Pull request merged**
