### PR TITLE
.NET 5.0 support and remove EOL .NET Core 3.0

### PR DESCRIPTION
**Pull request by punker76**
- .NET 5.0 support
- Remove EOL .NET Core 3.0
- Fix empty RECT in MonitorInfo (.NET 5 preview 7)
- Removing unused interop code
- Fixing or suppressing all newly introduced compiler warnings
- AD0001: Disabled because it throws an NRE
- Removing deprecated security attributes

### CODE REVIEW

**Comment by batzen** [comment]
RollForward only applies if the specified sdk version is not installed. Just increase the sdk version to 5 😉

**Comment by FreddyD-GH** [comment]
@punker76 I realize the .NET 5.0 work may not be completed yet, but are there any plans to release an updated NuGet package prior to the final .NET 5.0 release?  In particular, the bug where simply maximizing a window throws an exception is particularly annoying.

I tried out the code in the features/netcoreapp50 branch, and that appeared to fix it, but having an updated NuGet package (maybe a preview version) would be really nice.

**Comment by punker76** [comment]
@batzen Can we publish this? WDYT

**Review by batzen — APPROVED** [review]

**Comment by batzen** [comment]
@punker76 LGTM

**Pull request merged**
