### PR TITLE
ShadowWindowBehavior

### PR DESCRIPTION
**Pull request by jizc**
This behavior mimics the look and behavior of the native window shadows in Windows 10. It is meant to be used as an alternative to [GlowWindowBehavior](https://github.com/ControlzEx/ControlzEx/blob/WindowChromeNext/src/ControlzEx/Behaviors/GlowWindowBehavior.cs).

### Why not GlowWindow?
1. It mimics Visual Studio window glow, not Windows' own window shadows.
2. `ResizeBorderThickness` is directly tied to the visual thickness of the glow. `ShadowWindowBehavior` separates these as the shadow size is supposed to be static.
3. It was not possible to achieve the above points without completely rewriting GlowWindow, so I felt adding an alternative was the best approach.

### Notes
- The showcase has been expanded to easily test different behavior combinations (WindowChrome, WindowChrome + GlowWindow (default), WindowChrome + ShadowWindow).
- `GlowWindowBehavior` and `GlowWindow` has been slightly modified to fix issues with attaching/detaching `GlowWindowBehavior` at runtime.

### CODE REVIEW

**Comment by batzen** [comment]
Hi there,

thanks for contributing and bringing in new ideas.

I think the fixes you made regarding attach/detach are really needed and the idea of having the option to have a glow but no resize is also nice.

What we don't like is that we would have to maintain two nearly identical behaviors etc..
Using full size windows, like you did, also causes some performance issues while resizing the window etc..

We can definitely talk about improving the current behavior and window and make it more flexible.
Would you mind creating an issue where we can discuss further steps and ideas to improve the GlowBehavior in a way that makes it usable for you and maintainable for us?

The first step now taken by us is merging WindowChromeEx into develop as this was already planned for today as the changes are needed by MahApps.Metro and by Fluent.Ribbon.

It would be nice if you could create a PR with the fixes you made to the attach/detach code after we merged. If you don't want to do that i will apply your fixes to develop directly. I just don't want to take credit for your fixes, thus offering you to do them yourself. ;-)

**Comment by jizc** [comment]
Thank you for considering the PR 😃

I definitely get not wanting to maintain both behaviors. I just don't yet see any good way of getting what I need from `GlowWindowBehavior`. But perhaps with some discussion we could come up with a solution. I'll think on it and maybe create an issue as you suggest.

Concerning the use of full sized windows; I attempted to CPU profile the existing `GlowWindowBehavior` and it appeared that the `NativeMethods.SetWindowPos` method was the main resource hog. I figured having to call it for 4 windows was worse than 2. But you're saying that the full window sizes actually ends up being worse for performance? Also since I wanted to separate the resize border from the shadow, it would mean having 8 windows instead of 2 (unless there is a more clever way of doing it).

I'd be happy to make another PR with the fixes for `GlowWindowBehavior` and `GlowWindow`. I'll keep an eye out for the merge.

**Comment by batzen** [comment]
@jizc FYI, if you set the resize mode on your window and have the glow behavior attached it glows but does not act as a resize border. Totally forgot that that already works.

**Comment by jizc** [comment]
Thanks for the tip, but I've decided to just put WindowShadowBehavior directly in the projects I need it in. Since I wasn't using any ControlzEx internal stuff (with one very minor exception), it's really not a problem.

Looking forward to 4.0.0 and being able to switch back to NuGet 😃

**Pull request closed without merging**
